version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - '8080:8080'
  mysql:
    image: mysql/mysql-server:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - .:/app
    ports:
      - 3307:3306
