// Package scheme provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package scheme

// User defines model for User.
type User struct {
	AccountId int64  `json:"account_id"`
	Email     string `json:"email"`
	Id        int64  `json:"id"`
	Name      string `json:"name"`
}

// LimitQuery defines model for limitQuery.
type LimitQuery = int

// OffsetQuery defines model for offsetQuery.
type OffsetQuery = int

// UsersResponse defines model for UsersResponse.
type UsersResponse = []User

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	Limit  *LimitQuery  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`
}
