openapi: 3.0.1

tags:
  - name: User

servers:
  - url: http://localhost:8080/

paths:
  /users:
    get:
      tags:
        - Users
      summary: GetUsers Get Users
      operationId: GetUsers
      parameters:
        - $ref: "#/components/parameters/limitQuery"
        - $ref: "#/components/parameters/offsetQuery"
      responses:
        200:
          $ref: "#/components/responses/UsersResponse"
components:
  parameters:
    limitQuery:
      schema:
        type: integer
      name: limit
      in: query
      required: false
    offsetQuery:
      schema:
        type: integer
      name: offset
      in: query
      required: false
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        account_id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
      required:
        - id
        - account_id
        - name
        - email
  responses:
    UsersResponse:
      description: array of Users
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/User"
